version: '3.8'

services:
  fraudsight:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./data:/app/data
      - ./.env:/app/.env
    environment:
      - STREAMLIT_SERVER_MAX_UPLOAD_SIZE=3000
      - STREAMLIT_SERVER_MAX_MESSAGE_SIZE=3000
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 4G
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8501/_stcore/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
